# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0025273b96e69b7d8541bade41e756610041a1d17dc71a6de52f14bdd4560add5037caf046fde888fefd2815fa623cb2b7b866752d45ea6047938def1df928e9

test:
  secret_key_base: d0da69e6cb9604a016d938427be69703226e459c0835693e201dc383f98b66ffb09842ec83ce450dda8114a477ff6d9e98438050041bed8aa4e62ceb59eef5a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
